name: CI/CD Build & Deploy on Self-hosted Server

on:
  push:
    branches:
      - test
jobs:
  build-push:
    runs-on: self-hosted
    env:
      IMAGE_BACKEND: nor5/backend
      IMAGE_FRONTEND: nor5/frontend
    outputs:
      frontend_tag: ${{ steps.set_outputs.outputs.frontend_tag }}
      backend_tag: ${{ steps.set_outputs.outputs.backend_tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image frontend
        id: docker_frontend_build
        run: |
          IMAGE_FRONTEND_TAG=test-${GITHUB_SHA::7}
          echo "IMAGE_FRONTEND_TAG=$IMAGE_FRONTEND_TAG" >> $GITHUB_ENV
          sudo docker build -t $IMAGE_FRONTEND:$IMAGE_FRONTEND_TAG ./frontend
          sudo docker push $IMAGE_FRONTEND:$IMAGE_FRONTEND_TAG


      - name: Build and push Docker image backend
        id: docker_backend_build
        run: |
          IMAGE_BACKEND_TAG=test-${GITHUB_SHA::7}
          echo "IMAGE_BACKEND_TAG=$IMAGE_BACKEND_TAG" >> $GITHUB_ENV
          sudo docker build -t $IMAGE_BACKEND:$IMAGE_BACKEND_TAG ./backend
          sudo docker push $IMAGE_BACKEND:$IMAGE_BACKEND_TAG
      
      - name: Set output tags
        id: set_outputs
        run: |
          echo "::set-output name=frontend_tag::${IMAGE_FRONTEND_TAG}"
          echo "::set-output name=backend_tag::${IMAGE_BACKEND_TAG}"
      
     
  deploy-test:
    runs-on: self-hosted
    needs: build-push
    if: github.ref == 'refs/heads/test'
    env:
      IMAGE_FRONTEND_TAG: ${{ needs.build-push.outputs.frontend_tag }}
      IMAGE_BACKEND_TAG: ${{ needs.build-push.outputs.backend_tag }}
    steps:


      - name: Change backend name image in the compose file
        run: |

          sed -i "s|image: nor5/backend.*|image: nor5/backend:$IMAGE_BACKEND_TAG|" compose.test.yml

      - name: Change frontend name image in the compose file
  
        run: |
          
          sed -i "s|image: nor5/frontend.*|image: nor5/frontend:$IMAGE_FRONTEND_TAG|" compose.test.yml

      
      - name: Create .env file
        run: |
          cat > .env <<EOF
          DB_CONNECTION=${{ secrets.DB_CONNECTION_TEST }}
          DB_HOST=${{ secrets.DB_CONNECTION_TEST }}
          DB_PORT=${{ secrets.DB_PORT_TEST }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE_TEST }}
          MYSQL_USER=${{ secrets.MYSQL_USER_TEST }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD_TEST }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_PASSWORD_TEST }}
          EOF
  
      - name: Cleanup before deployment
        run: |
          sudo docker compose -f compose.test.yml down -v --remove-orphans
          sudo docker image prune -af
          sudo docker volume prune -f
      
      - name: Run Compose
        run: |
          sudo docker compose -f compose.test.yml up -d --remove-orphans
          
